#!/usr/bin/perl -w

use File::Copy;

if (! -d ".legit") {
    die "legit-branch: error: no .legit directory containing legit repository exists\n"
}
if ( ! -f '.legit/log') {
    die "legit-branch: error: your repository does not have any commits yet\n";
}

if (!@ARGV) {
    # list all branch names in sorted order
    opendir my $dir, ".legit/branch/";
    my @files = readdir $dir;
    @files = sort @files;
    foreach $file (@files) {
        next if ($file =~ /^\./);
        print "$file\n";
    } 
    exit 0;
}

# check for valid arguments
if (@ARGV > 2) {
    # args can not be more than 2
    die "usage: legit-branch [-d] <branch>\n";
} elsif (@ARGV == 2 && $ARGV[0] ne '-d') {
    # args can only be 2 if using -d flag
    die "usage: legit-branch [-d] <branch>\n";
} elsif ($ARGV[0] eq '-d' && @ARGV != 2) {
    # args must be 2 if using -d flag
    die "usage: legit-branch [-d] <branch>\n";
}

$delete = 0;
$new = 0;

if (@ARGV == 2) {
    $bname = $ARGV[1];
    $delete = 1;
} else {
    $bname = $ARGV[0];
    $new = 1;
}

# check for invalid branch names
if ( $bname !~ /[a-zA-Z]/) {
    die "legit-branch: error: invalid branch name '$bname'\n";
} elsif ($bname =~ /^-/) {
    die "usage: legit-branch [-d] <branch>\n";
}

chomp $bname;

# check if branch exist
if ( -f ".legit/branch/$bname" ) {
    # create new branch fails
    die "legit-branch: error: branch '$bname' already exists\n" if $new;
} else {
    # delete non-existent branch fails
    die "legit-branch: error: branch '$bname' does not exist\n" if $delete;
}

# create new branch
if ($new) {
    open my $HEAD, '<', '.legit/HEAD';
    my $hbranch = <$HEAD>;
    chomp $hbranch;
    copy(".legit/$hbranch", ".legit/branch/$bname");
    exit 0;
}

# delete branch
if ($delete) {
    if ($bname =~ /^master$/) {
        die "legit-branch: error: can not delete branch 'master'\n";
    }

    # Detect unmerged work error
    open my $F, '<', ".legit/branch/$bname";
    $bcommit = <$F>;
    close $F;
    chomp $bcommit;
    
    # Get all file hashes from branch to be deleted 
    open $F, '<', ".legit/objects/$bcommit";
    @items = <$F>;
    close $F;

    %blobs = ();
    foreach $line (@items) {
        my ($type, $hash, $name) = split(' ', $line);
        next if "$type" eq 'parent';
        chomp $name;
        $blobs{$name} = $hash;
    }

    # Get all file hashes from master branch
    open $F, '<', ".legit/branch/master";
    $mcommit = <$F>;
    close $F;
    chomp $mcommit;
    
    # Get all file hashes from branch to be deleted 
    open $F, '<', ".legit/objects/$mcommit";
    @items = <$F>;
    close $F;
    %mblobs = ();
    foreach $line (@items) {
        my ($type, $hash, $name) = split(' ', $line);
        next if "$type" eq 'parent';
        chomp $name;
        $mblobs{$name} = $hash;
    }
    
    while(($fname, $fhash) = each %blobs) {
        # if any to be deleted file is not in master, error
        if (exists $mblobs{$fname} && $mblobs{$fname} eq $fhash) {
            next;
        } else {
            die "legit-branch: error: branch '$bname' has unmerged changes\n"
        }
    }

    unlink ".legit/branch/$bname"; 
    print "Deleted branch '$bname'\n";
    exit 0;
}

