#!/bin/dash

# Test if no repo
if [ ! -d '.legit' ]
then
    echo "legit-log: error: no .legit directory containing legit repository exists" 1>&2
    exit 1
fi

if [ ! -f '.legit/log' ]
then
    echo "legit-log: error: your repository does not have any commits yet" 1>&2
    exit 1
fi

cat '.legit/log'
exit 0
