#!/bin/dash



# check for commits
if [ ! -f '.legit/commit' ]
then
    echo "legit-status: error: your repository does not have any commits yet" 1>&2
    exit 1
fi

# create temporary status file
touch '.legit/status'
# Get recent HEAD commit
branch=`cat '.legit/HEAD'`
rc=`cat ".legit/$branch"`

# recent commit object is at .legit/objects/$rc
rcPath="objects/$rc"

for file in *
do
    if [ ! -f "$file" ]
    then
        continue
    fi
    # Check if file's name exist in previous commit
    blobRc=`egrep " $file$" ".legit/$rcPath"`
    if [ -z "$blobRc" ]
    then
        # Check if file's name exist in index
        if ! egrep " $file$" ".legit/index" >/dev/null
        then
            # Untracked
            echo "$file - untracked" >>'.legit/status'
        else
            # Added to index
            echo "$file - added to index" >>'.legit/status'
        fi
        continue
    else
        # Compute working directory file sha hash
        size=`ls -l "$file" | cut -d' ' -f4`
        content=`cat "$file"`
        wdSha=`echo "blob$size$content" | sha1sum | egrep -o '[^ -]*'`
        rcSha=`echo "$blobRc" | cut -d' ' -f2`
        # Get index hash
        indexLine=`egrep " $file$" ".legit/index"`
        indSha=`echo "$indexLine" | cut -d' ' -f2`

        # Check if index hash is same as recent commit hash
        # To see if changes were staged
        if echo "$indSha" | egrep "^$rcSha$" >/dev/null
        then
            if echo "$wdSha" | egrep "^$rcSha$" >/dev/null
            then
                # same as repo
                echo "$file - same as repo" >>'.legit/status'
            else
                # changes are not staged for commit
                echo "$file - file changed, changes not staged for commit" >>'.legit/status'
            fi
        else
            # there are changes staged
            # Check if working directory hash is same as index hash
            if echo "$wdSha" | egrep "^$indSha$" >/dev/null
            then
                # same as index sha
                echo "$file - file changed, changes staged for commit" >>'.legit/status'
            else
                if [ -z "$indSha" ]
                then
                    # file not in index, but was in recent commit
                    echo "$file - untracked" >>'.legit/status'
                    continue
                fi
                # different to index sha
                echo "$file - file changed, different changes staged for commit" >>'.legit/status'
            fi
        fi
    fi
done

files=`cat ".legit/$rcPath" | egrep "^blob"`
echo "$files" |
while read -r line
do
    name=`echo "$line" | cut -d' ' -f3-`
    if [ -f "$name" ] || [ -z "$name" ]
    then
        # file still exists in directory
        continue
    fi
    # Check if filename exist in index
    if egrep " $name$" ".legit/index" >/dev/null
    then
        indexLine=`egrep " $name$" ".legit/index"`
        blobRc=`egrep " $name$" ".legit/$rcPath"`
        rcSha=`echo "$blobRc" | cut -d' ' -f2`
        indSha=`echo "$indexLine" | cut -d' ' -f2`
        # Check if index hash is same as recent commit hash
        if echo "$rcSha" | egrep "^$indSha$" >/dev/null
        then
            # file deleted
            # same as index sha, not yet staged
            echo "$name - file deleted" >>'.legit/status'
        else
            # file deleted, different changes staged for commit
            # different to index sha
            echo "$name - file deleted, different changes staged for commit" >>'.legit/status'
        fi       
    else
        # File no longer in both working directory and index
        echo "$name - deleted" >>'.legit/status'
    fi
done


sort '.legit/status'
rm '.legit/status'
